### ISSUE TITLE
 R015: image reconstruction error on Prisma 3T VD13D

### ISSUE THREAD

**Issue by RAWaggoner** [CMRR-C2P/MB#152]
Since installing R015, most of the time after the first few volumes of a multi-band acquisition the scan stops with an image reconstruction error.  To me this sounds similar to issue #130, but we tried the two suggestions you gave to fix that issue with no success.  R014 was working fine.

Here are the savelogs
https://www.dropbox.com/s/92m3etm18d2v70h/RIKEN_savelogs.zip?dl=0

Thanks

**Comment by egwalsh** [comment]
Same situation here at Brown in Providence.  VD13D on a Prisma 3T.

**Comment by eauerbach** [comment]
Can someone try this update and let me know if it improves anything (I do not have a VD13D test system anymore):

https://dl.dropboxusercontent.com/u/5314394/libCMRR_MBIcePrg2D.zip

Uncompress the .zip, replace the existing `libCMRR_MBIcePrg2D.so` in `C:\MedCom\MriCustomer\Ice\` with the updated one, then go to **System/Control/Meas & Recon** and restart the **MrIrisContainer@mars** process.

**Comment by egwalsh** [comment]
Will try in an hour or so.

Thanks!

EGW.

Edward G. Walsh, Ph.D.

Brown University, Departments of Neuroscience, Diagnostic Imaging and
Institute for Brain Science

University of Rhode Island, Department of Physics

Brown University Magnetic Resonance Facility, Associate Director for MRI
Physics

Box G-LN

Sidney E. Frank Hall

185 Meeting Street

Providence, RI 02912

401-863-6525

**Comment by egwalsh** [comment]
Hi Eddie,

Still failed.  Ran OK once and reconstructed.  On the second scan, it quit
in the middle of the run with same error messages as before.

EGW.

Edward G. Walsh, Ph.D.

Brown University, Departments of Neuroscience, Diagnostic Imaging and
Institute for Brain Science

University of Rhode Island, Department of Physics

Brown University Magnetic Resonance Facility, Associate Director for MRI
Physics

Box G-LN

Sidney E. Frank Hall

185 Meeting Street

Providence, RI 02912

401-863-6525

**Comment by romainVala** [comment]
Hello
We add the same problem yesterday with the new sequence, on our prisam at CENIR.
may be can you provide the old sequence with a new licence file ?
so that we can run the sequence waiting you fix it ...

Many thanks for your effort
Romain

**Comment by RAWaggoner** [comment]
So far the updated SO file seems to have fixed the problem for us.  We installed the new file then did 15 runs without a crash.  We then put the old SO file back in and got the error.  After reinstalling the new SO files we did 5 more runs without the error.  

I can't yer say 100% that the problem is fixed, but before the problem was occurring after just one or two runs, so it looks very promising.

We just followed your instructions, so I am not sure why it worked for us and not at Brown.

Thank,
Allen

**Comment by claus-magdeburg** [comment]
I will exchange the file soon, but extensive testing will not be possible befor 4pm German time. Will get back to you then.

**Comment by romainVala** [comment]
I also made the change, and it improves thing. We still do not see the bug, although we only did a few acquisition.

**Comment by swrieger** [comment]
We have replaced the .so but the sequence still crashes.

**Comment by swrieger** [comment]
Hi Eddie,

could you let us know soon if there is a chance of getting R014 back (with an extended expiry date)? It's just that this is causing chaos with ongoing studies and the sooner I know if we have to cancel participants, the better.

Best wishes,

Seb

**Comment by claus-magdeburg** [comment]
I'm not sure how conclusive my tests were but there are indications that the new file has fixed the problem or at least reduced it: 

I started with the new so-file: 3 runs without a crash.

I went back to the old file and restarted the MrIrisContainer@mars process. Now, the scanner wanted to be brave and avoided any crashes for three runs. However, in run 4 it finally crashed.

Back to the new so-file, restart of the MrIrisContainer@mars process. After that I got 16 runs without crash before I stopped testing for today.

We will continue using the sequence and report here if the problem returns.

In any case for the very prompt reaction!

Claus

**Comment by eauerbach** [comment]
Can those of you who are still having the problem please download this updated archive from the web site and do a full reinstall using the installation .bat script. This will ensure that the files are in the correct locations without inadvertent duplicates, and it also performs a full reboot of the MaRS to be absolutely certain that the new library is loaded:

http://www.cmrr.umn.edu/multiband/Downloads-Seq/CMRR_MB_EPI_VD13D_R015.zip

Otherwise I have no idea why the updated library would fix the problem for some but not others...the change I made effectively does revert the only meaningful change between R014 and R015.

In more detail: in R015 I added a step which attempts to very thoroughly release any possibly lingering bits of GPU memory between scans. This seems to work fine in VE11x, but it looks like it causes problems with the very old GPU libraries in use in VD13D. I assume the problem everyone is seeing occurs when you run multiple scans one after another and the reconstructions overlap in time. The memory cleanup process is executed at the end of a reconstruction. If a previous reconstruction is still running after a new scan is started, perhaps when the previous reconstruction finishes its cleanup process crashes the current scan.

**Comment by claus-magdeburg** [comment]
_I assume the problem everyone is seeing occurs when you run multiple scans one after another and the reconstructions overlap in time._

I doubt that that is the full explanation. We definitely had cases where the system crashed at the start of the first multiband scan.

Claus

**Comment by eauerbach** [comment]
In all versions (at least prior to VE11x), sometimes the first MB reconstruction will fail (especially the first scan after a system reboot). This is a known issue with no solution. Accessing the GPU hardware for the first time can cause a brief blocking delay resulting in a nearly immediate failure occurring at the start of the first MB scan. If you restart the scan at that point it should proceed normally and remain fine thereafter (e.g. until the next reboot).

If that is different from what you are seeing, however, send me a savelog and I will look into it.

**Comment by rogiedodgie** [comment]
Hi,
Roger Newman-Norlund with Chris Rorden's group here at USC Columbia, SC.  
We had problems with MB as well.
After applying the latest patch to our Prisma Fit (VD13D) we haven't had any issues so far, will post if we do.
Here is our system information in case it helps others
-Roger

![img_20170309_144458171](https://cloud.githubusercontent.com/assets/26310853/23767915/4b867408-04d8-11e7-85ed-2392aa0af1c3.jpg)
![img_20170309_144439602](https://cloud.githubusercontent.com/assets/26310853/23767916/4b8e94b2-04d8-11e7-9ce5-8e20391ac06e.jpg)

**Comment by ltala** [comment]
Hello All,
Thanks for the quick response. After installing the fix yesterday we ran test sequences successfully. We also ran today with no issues- our typical scans use 6 MB back to back plus MPR/SPC. I am from NIH on a Prisma VD13D. 
Thanks-Lori

**Comment by swrieger** [comment]
Hi Eddie,

not sure why replacing the .so hadn't worked. Having downloaded the new archive and re-installed using the .bat, everything seems back to normal now.

When we did get the error, it was not always at the start of a run, sometimes it was at the end. Also, occasionally it required full system reboot (not just MARS) to fix. Finally, the error occurred not just at the first MB run after a reboot, but several times between reboots. 

Thanks for your help!

Cheers,
Seb

**Comment by tvickery** [comment]
We are having very similar issues on VE11C Prisma at University of Delaware. Will same solution recommended above work?

**Comment by eauerbach** [comment]
My understanding is that this specific problem should apply only to VD13D (and possibly VD13A/B/C but perhaps we don't have many users on those versions anymore). If you see it again please collect a savelog and I will have a look at it.
