### ISSUE TITLE
Unable to run MB on VE12U without GPU

### ISSUE THREAD

**Issue by andrewtmorgan** [CMRR-C2P/MB#229]
We have installed the CMRR MB sequence on our Terra system (baseline VE12U without GPU), but cannot run it. We get the following errors:

Cannot load DLL 'libCMRR_MBIcePrg2D.so'
Load error reason: libcuda.so.1: cannot open shared object file: No such file or directory

As far as I can tell, there were no issues during the install. We needed to run embedded control mode, but no warnings or errors were given until protocol runtime. I assume this problem has to do with the CUDA driver not being properly installed on the MARS. I can provide diagnostics and more error reports to help figure out the issue.

Thanks,
Andrew

[cmrr_mb_errorlog.log](https://github.com/CMRR-C2P/MB/files/3201332/cmrr_mb_errorlog.log)

**Comment by eauerbach** [comment]
When did you download the .zip file? If it was before May 16 then please download a new copy and run the installer again. There was a problem with the original installer specific to VE12U (if you missed the error message it would appear that everything was installed correctly).

**Comment by andrewtmorgan** [comment]
Today I reinstalled with a freshly downloaded version but the problem persisted. Is it possible that the cuda driver is not properly installing on the Mars? If so, is there a way to test it?

Thanks,
Tyler

**Comment by eauerbach** [comment]
Can you try it again; I just uploaded another update.

Yes, the problem is that if you do not have a GPU, a CUDA driver is not installed when the MaRS software is loaded. But my ICE program requires a driver to exist, even if it is not used. So my installer script will install a dummy driver if one is not found. There were initially a couple issues with the VE12U version of the script preventing this from working properly, however, which I hope are now fixed.

**Comment by andrewtmorgan** [comment]
Unfortunately that did not solve the issue. Would be helpful to send you a diagnostics report?

I will be at the scanner a little longer tonight if there is something I can collect and provide.

Thanks again,
Tyler

**Comment by eauerbach** [comment]
Yes, if you could collect and send me a savelog that would help.

**Comment by andrewtmorgan** [comment]
Here is a link for the savelog:

https://cloud.psy.gla.ac.uk/index.php/s/kfnFgrTXfpHj9EO

**Comment by eauerbach** [comment]
I uploaded another update; let me know if there is still a problem.

**Comment by andrewtmorgan** [comment]
Okay, I tested the new one this morning. It doesn't work, but now the error is looks related to a different file:

Cannot load DLL 'libCMRR_MBIcePrg2D.so'.
Load error reason: libnvidia-fatbinaryloader.so.375.26: cannot open shared object file: No such file or directory

Here is a link to today's savelog:
https://cloud.psy.gla.ac.uk/index.php/s/NBqaK0TTJZIRFuh

**Comment by andrewtmorgan** [comment]
I am just checking back in with this. If there is any other information that is needed, please let me know and I can get that to you tomorrow.

**Comment by eauerbach** [comment]
That is yet another interesting twist; I have posted another new version. Must be getting close... 😬

**Comment by andrewtmorgan** [comment]
I have tried again without success (it looks like the same error). Here is the log:

https://cloud.psy.gla.ac.uk/index.php/s/ZA7wdjnPUcP69Mn

If you don't mind me asking, are we the first VE12 site attempting to run the MB sequence? We are wondering if this could be a general VE12 issue or if it specific to our system lacking the GPU.

**Comment by eauerbach** [comment]
Yes, it works fine at other VE12U sites with GPU and pre-VE12U sites without GPU; this is a problem specific to VE12U sites without GPU. I'm actually surprised there are VE12U sites without GPU.

Anyway, sorry, I don't have access to a VE12U system and won't for another month at least, so I'm working somewhat blind and making educated guesses. Thanks for being the tester.

At this point I'm pretty confident the fixes I have implemented in the installer will work on a clean system, but on your system one of the intermediate failed attempts is preventing it from working. So if you were to reinstall the MaRS software it should work, but to avoid that and save some time, please just run this command from the host (with the system fully up and running):

`ssh root@mars "ln -sf /opt/medcom/MriCustomer/ice/libnvidia-fatbinaryloader.so.375.26.eja /usr/lib/libnvidia-fatbinaryloader.so.375.26"`

That _should_ take care of it immediately, and if you gain a GPU at some point in the future it will be used automatically.

**Comment by andrewtmorgan** [comment]
Okay, it works now! Thanks very much for how much you have put into getting this going. I would guess we are probably the only VE12U site (or one of the only sites) without a GPU, but if not, this works as a solution.
